### ISSUE TITLE
가상선택자 ::before 적용이 안 되는 이슈 

### ISSUE THREAD

**Issue by amorfati0310** [childrenOfCrong/HanTang#28]
기존에 가상 선택자로 백을 덮었던 부분이 width: auto height: auto로 되면서 아무것도 안 뜨는데 
왜 적용이 안되는지 잘 모르겠습니다 ;ㅁ; 
```css
  &::before {
    content: "";
    display: block;
    width: 7rem;
    height: 11.5rem;
    background: red;
    transform: rotateY(90deg);
    position: absolute;
    z-index: 1000;
  }
```
